/*----- PROTECTED REGION ID(ZygoZMI4104CClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        ZygoZMI4104CClass.h
//
// description : Include for the ZygoZMI4104C root class.
//               This class is the singleton class for
//                the ZygoZMI4104C device class.
//               It contains all properties and methods which the 
//               ZygoZMI4104C requires only once e.g. the commands.
//
// project :     ZygoZMI4104C
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef ZygoZMI4104CClass_H
#define ZygoZMI4104CClass_H

#include <tango.h>
#include <ZygoZMI4104C.h>


/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104CClass.h


namespace ZygoZMI4104C_ns
{
/*----- PROTECTED REGION ID(ZygoZMI4104CClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104CClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute samplingFrequency class definition
class samplingFrequencyAttrib: public Tango::Attr
{
public:
	samplingFrequencyAttrib():Attr("samplingFrequency",
			Tango::DEV_ULONG, Tango::READ_WRITE) {};
	~samplingFrequencyAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_samplingFrequency(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->write_samplingFrequency(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_samplingFrequency_allowed(ty);}
};

//	Attribute axis1LedState class definition
class axis1LedStateAttrib: public Tango::Attr
{
public:
	axis1LedStateAttrib():Attr("axis1LedState",
			Tango::DEV_STRING, Tango::READ) {};
	~axis1LedStateAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis1LedState(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis1LedState_allowed(ty);}
};

//	Attribute axis2LedState class definition
class axis2LedStateAttrib: public Tango::Attr
{
public:
	axis2LedStateAttrib():Attr("axis2LedState",
			Tango::DEV_STRING, Tango::READ) {};
	~axis2LedStateAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis2LedState(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis2LedState_allowed(ty);}
};

//	Attribute axis3LedState class definition
class axis3LedStateAttrib: public Tango::Attr
{
public:
	axis3LedStateAttrib():Attr("axis3LedState",
			Tango::DEV_STRING, Tango::READ) {};
	~axis3LedStateAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis3LedState(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis3LedState_allowed(ty);}
};

//	Attribute axis4LedState class definition
class axis4LedStateAttrib: public Tango::Attr
{
public:
	axis4LedStateAttrib():Attr("axis4LedState",
			Tango::DEV_STRING, Tango::READ) {};
	~axis4LedStateAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis4LedState(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis4LedState_allowed(ty);}
};

//	Attribute referenceAxisLedState class definition
class referenceAxisLedStateAttrib: public Tango::Attr
{
public:
	referenceAxisLedStateAttrib():Attr("referenceAxisLedState",
			Tango::DEV_STRING, Tango::READ) {};
	~referenceAxisLedStateAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_referenceAxisLedState(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_referenceAxisLedState_allowed(ty);}
};

//	Attribute currentPrecision class definition
class currentPrecisionAttrib: public Tango::Attr
{
public:
	currentPrecisionAttrib():Attr("currentPrecision",
			Tango::DEV_ENUM, Tango::READ_WRITE) {};
	~currentPrecisionAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_currentPrecision(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->write_currentPrecision(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_currentPrecision_allowed(ty);}
	virtual bool same_type(const type_info &in_type) {return typeid(currentPrecisionEnum) == in_type;}
	virtual string get_enum_type() {return string("currentPrecisionEnum");}
};

//	Attribute axis1PositionValue class definition
class axis1PositionValueAttrib: public Tango::Attr
{
public:
	axis1PositionValueAttrib():Attr("axis1PositionValue",
			Tango::DEV_DOUBLE, Tango::READ) {};
	~axis1PositionValueAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis1PositionValue(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis1PositionValue_allowed(ty);}
};

//	Attribute axis2PositionValue class definition
class axis2PositionValueAttrib: public Tango::Attr
{
public:
	axis2PositionValueAttrib():Attr("axis2PositionValue",
			Tango::DEV_DOUBLE, Tango::READ) {};
	~axis2PositionValueAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis2PositionValue(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis2PositionValue_allowed(ty);}
};

//	Attribute axis3PositionValue class definition
class axis3PositionValueAttrib: public Tango::Attr
{
public:
	axis3PositionValueAttrib():Attr("axis3PositionValue",
			Tango::DEV_DOUBLE, Tango::READ) {};
	~axis3PositionValueAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis3PositionValue(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis3PositionValue_allowed(ty);}
};

//	Attribute axis4PositionValue class definition
class axis4PositionValueAttrib: public Tango::Attr
{
public:
	axis4PositionValueAttrib():Attr("axis4PositionValue",
			Tango::DEV_DOUBLE, Tango::READ) {};
	~axis4PositionValueAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis4PositionValue(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis4PositionValue_allowed(ty);}
};

//	Attribute axis1OpticalPowerValue class definition
class axis1OpticalPowerValueAttrib: public Tango::Attr
{
public:
	axis1OpticalPowerValueAttrib():Attr("axis1OpticalPowerValue",
			Tango::DEV_DOUBLE, Tango::READ) {};
	~axis1OpticalPowerValueAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis1OpticalPowerValue(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis1OpticalPowerValue_allowed(ty);}
};

//	Attribute axis2OpticalPowerValue class definition
class axis2OpticalPowerValueAttrib: public Tango::Attr
{
public:
	axis2OpticalPowerValueAttrib():Attr("axis2OpticalPowerValue",
			Tango::DEV_DOUBLE, Tango::READ) {};
	~axis2OpticalPowerValueAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis2OpticalPowerValue(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis2OpticalPowerValue_allowed(ty);}
};

//	Attribute axis3OpticalPowerValue class definition
class axis3OpticalPowerValueAttrib: public Tango::Attr
{
public:
	axis3OpticalPowerValueAttrib():Attr("axis3OpticalPowerValue",
			Tango::DEV_DOUBLE, Tango::READ) {};
	~axis3OpticalPowerValueAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis3OpticalPowerValue(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis3OpticalPowerValue_allowed(ty);}
};

//	Attribute axis4OpticalPowerValue class definition
class axis4OpticalPowerValueAttrib: public Tango::Attr
{
public:
	axis4OpticalPowerValueAttrib():Attr("axis4OpticalPowerValue",
			Tango::DEV_DOUBLE, Tango::READ) {};
	~axis4OpticalPowerValueAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis4OpticalPowerValue(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis4OpticalPowerValue_allowed(ty);}
};

//	Attribute axis1OffsetPositionValue class definition
class axis1OffsetPositionValueAttrib: public Tango::Attr
{
public:
	axis1OffsetPositionValueAttrib():Attr("axis1OffsetPositionValue",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~axis1OffsetPositionValueAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis1OffsetPositionValue(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->write_axis1OffsetPositionValue(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis1OffsetPositionValue_allowed(ty);}
};

//	Attribute axis2OffsetPositionValue class definition
class axis2OffsetPositionValueAttrib: public Tango::Attr
{
public:
	axis2OffsetPositionValueAttrib():Attr("axis2OffsetPositionValue",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~axis2OffsetPositionValueAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis2OffsetPositionValue(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->write_axis2OffsetPositionValue(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis2OffsetPositionValue_allowed(ty);}
};

//	Attribute axis3OffsetPositionValue class definition
class axis3OffsetPositionValueAttrib: public Tango::Attr
{
public:
	axis3OffsetPositionValueAttrib():Attr("axis3OffsetPositionValue",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~axis3OffsetPositionValueAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis3OffsetPositionValue(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->write_axis3OffsetPositionValue(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis3OffsetPositionValue_allowed(ty);}
};

//	Attribute axis4OffsetPositionValue class definition
class axis4OffsetPositionValueAttrib: public Tango::Attr
{
public:
	axis4OffsetPositionValueAttrib():Attr("axis4OffsetPositionValue",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~axis4OffsetPositionValueAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis4OffsetPositionValue(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->write_axis4OffsetPositionValue(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis4OffsetPositionValue_allowed(ty);}
};

//	Attribute axis1PresetPositionValue class definition
class axis1PresetPositionValueAttrib: public Tango::Attr
{
public:
	axis1PresetPositionValueAttrib():Attr("axis1PresetPositionValue",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~axis1PresetPositionValueAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis1PresetPositionValue(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->write_axis1PresetPositionValue(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis1PresetPositionValue_allowed(ty);}
};

//	Attribute axis2PresetPositionValue class definition
class axis2PresetPositionValueAttrib: public Tango::Attr
{
public:
	axis2PresetPositionValueAttrib():Attr("axis2PresetPositionValue",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~axis2PresetPositionValueAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis2PresetPositionValue(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->write_axis2PresetPositionValue(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis2PresetPositionValue_allowed(ty);}
};

//	Attribute axis3PresetPositionValue class definition
class axis3PresetPositionValueAttrib: public Tango::Attr
{
public:
	axis3PresetPositionValueAttrib():Attr("axis3PresetPositionValue",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~axis3PresetPositionValueAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis3PresetPositionValue(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->write_axis3PresetPositionValue(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis3PresetPositionValue_allowed(ty);}
};

//	Attribute axis4PresetPositionValue class definition
class axis4PresetPositionValueAttrib: public Tango::Attr
{
public:
	axis4PresetPositionValueAttrib():Attr("axis4PresetPositionValue",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~axis4PresetPositionValueAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis4PresetPositionValue(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->write_axis4PresetPositionValue(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis4PresetPositionValue_allowed(ty);}
};

//	Attribute axis1BiasMode class definition
class axis1BiasModeAttrib: public Tango::Attr
{
public:
	axis1BiasModeAttrib():Attr("axis1BiasMode",
			Tango::DEV_STRING, Tango::READ_WRITE) {};
	~axis1BiasModeAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis1BiasMode(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->write_axis1BiasMode(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis1BiasMode_allowed(ty);}
};

//	Attribute axis2BiasMode class definition
class axis2BiasModeAttrib: public Tango::Attr
{
public:
	axis2BiasModeAttrib():Attr("axis2BiasMode",
			Tango::DEV_STRING, Tango::READ_WRITE) {};
	~axis2BiasModeAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis2BiasMode(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->write_axis2BiasMode(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis2BiasMode_allowed(ty);}
};

//	Attribute axis3BiasMode class definition
class axis3BiasModeAttrib: public Tango::Attr
{
public:
	axis3BiasModeAttrib():Attr("axis3BiasMode",
			Tango::DEV_STRING, Tango::READ_WRITE) {};
	~axis3BiasModeAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis3BiasMode(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->write_axis3BiasMode(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis3BiasMode_allowed(ty);}
};

//	Attribute axis4BiasMode class definition
class axis4BiasModeAttrib: public Tango::Attr
{
public:
	axis4BiasModeAttrib():Attr("axis4BiasMode",
			Tango::DEV_STRING, Tango::READ_WRITE) {};
	~axis4BiasModeAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_axis4BiasMode(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->write_axis4BiasMode(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_axis4BiasMode_allowed(ty);}
};

//	Attribute interferometerConfiguration class definition
class interferometerConfigurationAttrib: public Tango::Attr
{
public:
	interferometerConfigurationAttrib():Attr("interferometerConfiguration",
			Tango::DEV_STRING, Tango::READ_WRITE) {};
	~interferometerConfigurationAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_interferometerConfiguration(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->write_interferometerConfiguration(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_interferometerConfiguration_allowed(ty);}
};

//	Attribute sisFirmwareVersion class definition
class sisFirmwareVersionAttrib: public Tango::Attr
{
public:
	sisFirmwareVersionAttrib():Attr("sisFirmwareVersion",
			Tango::DEV_STRING, Tango::READ) {};
	~sisFirmwareVersionAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_sisFirmwareVersion(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_sisFirmwareVersion_allowed(ty);}
};

//	Attribute sisBoardVersion class definition
class sisBoardVersionAttrib: public Tango::Attr
{
public:
	sisBoardVersionAttrib():Attr("sisBoardVersion",
			Tango::DEV_STRING, Tango::READ) {};
	~sisBoardVersionAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_sisBoardVersion(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_sisBoardVersion_allowed(ty);}
};

//	Attribute zygoFirmwareVersion class definition
class zygoFirmwareVersionAttrib: public Tango::Attr
{
public:
	zygoFirmwareVersionAttrib():Attr("zygoFirmwareVersion",
			Tango::DEV_STRING, Tango::READ) {};
	~zygoFirmwareVersionAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_zygoFirmwareVersion(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_zygoFirmwareVersion_allowed(ty);}
};

//	Attribute zygoBoardVersion class definition
class zygoBoardVersionAttrib: public Tango::Attr
{
public:
	zygoBoardVersionAttrib():Attr("zygoBoardVersion",
			Tango::DEV_STRING, Tango::READ) {};
	~zygoBoardVersionAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_zygoBoardVersion(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_zygoBoardVersion_allowed(ty);}
};

//	Attribute zygoSerialNumber class definition
class zygoSerialNumberAttrib: public Tango::Attr
{
public:
	zygoSerialNumberAttrib():Attr("zygoSerialNumber",
			Tango::DEV_STRING, Tango::READ) {};
	~zygoSerialNumberAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_zygoSerialNumber(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_zygoSerialNumber_allowed(ty);}
};

//	Attribute continuousSamplingAxes class definition
class continuousSamplingAxesAttrib: public Tango::Attr
{
public:
	continuousSamplingAxesAttrib():Attr("continuousSamplingAxes",
			Tango::DEV_STRING, Tango::READ_WRITE) {};
	~continuousSamplingAxesAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_continuousSamplingAxes(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->write_continuousSamplingAxes(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_continuousSamplingAxes_allowed(ty);}
};

//	Attribute continuousSamplingSize class definition
class continuousSamplingSizeAttrib: public Tango::Attr
{
public:
	continuousSamplingSizeAttrib():Attr("continuousSamplingSize",
			Tango::DEV_ULONG, Tango::READ_WRITE) {};
	~continuousSamplingSizeAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_continuousSamplingSize(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->write_continuousSamplingSize(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_continuousSamplingSize_allowed(ty);}
};

//	Attribute cecAxes class definition
class cecAxesAttrib: public Tango::Attr
{
public:
	cecAxesAttrib():Attr("cecAxes",
			Tango::DEV_STRING, Tango::READ_WRITE) {};
	~cecAxesAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_cecAxes(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->write_cecAxes(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_cecAxes_allowed(ty);}
};

//	Attribute continuousScanPositionMeanValue class definition
class continuousScanPositionMeanValueAttrib: public Tango::Attr
{
public:
	continuousScanPositionMeanValueAttrib():Attr("continuousScanPositionMeanValue",
			Tango::DEV_DOUBLE, Tango::READ) {};
	~continuousScanPositionMeanValueAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_continuousScanPositionMeanValue(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_continuousScanPositionMeanValue_allowed(ty);}
};

//	Attribute continuousScanPositionStdDev class definition
class continuousScanPositionStdDevAttrib: public Tango::Attr
{
public:
	continuousScanPositionStdDevAttrib():Attr("continuousScanPositionStdDev",
			Tango::DEV_DOUBLE, Tango::READ) {};
	~continuousScanPositionStdDevAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ZygoZMI4104C *>(dev))->read_continuousScanPositionStdDev(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ZygoZMI4104C *>(dev))->is_continuousScanPositionStdDev_allowed(ty);}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command ResetMeasurementAxis class definition
class ResetMeasurementAxisClass : public Tango::Command
{
public:
	ResetMeasurementAxisClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	ResetMeasurementAxisClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~ResetMeasurementAxisClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<ZygoZMI4104C *>(dev))->is_ResetMeasurementAxis_allowed(any);}
};

//	Command StartContinuousAcquisition class definition
class StartContinuousAcquisitionClass : public Tango::Command
{
public:
	StartContinuousAcquisitionClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	StartContinuousAcquisitionClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~StartContinuousAcquisitionClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<ZygoZMI4104C *>(dev))->is_StartContinuousAcquisition_allowed(any);}
};

//	Command StopContinnuousAcquisition class definition
class StopContinnuousAcquisitionClass : public Tango::Command
{
public:
	StopContinnuousAcquisitionClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	StopContinnuousAcquisitionClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~StopContinnuousAcquisitionClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<ZygoZMI4104C *>(dev))->is_StopContinnuousAcquisition_allowed(any);}
};

//	Command EnableCyclicErrorCompensation class definition
class EnableCyclicErrorCompensationClass : public Tango::Command
{
public:
	EnableCyclicErrorCompensationClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	EnableCyclicErrorCompensationClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~EnableCyclicErrorCompensationClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<ZygoZMI4104C *>(dev))->is_EnableCyclicErrorCompensation_allowed(any);}
};

//	Command DisableCyclicErrorCompensation class definition
class DisableCyclicErrorCompensationClass : public Tango::Command
{
public:
	DisableCyclicErrorCompensationClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	DisableCyclicErrorCompensationClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~DisableCyclicErrorCompensationClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<ZygoZMI4104C *>(dev))->is_DisableCyclicErrorCompensation_allowed(any);}
};

//	Command ResetMeasurementSystem class definition
class ResetMeasurementSystemClass : public Tango::Command
{
public:
	ResetMeasurementSystemClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	ResetMeasurementSystemClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~ResetMeasurementSystemClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<ZygoZMI4104C *>(dev))->is_ResetMeasurementSystem_allowed(any);}
};


/**
 *	The ZygoZMI4104CClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  ZygoZMI4104CClass : public Tango::DeviceClass
#else
class ZygoZMI4104CClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(ZygoZMI4104CClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104CClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static ZygoZMI4104CClass *init(const char *);
		static ZygoZMI4104CClass *instance();
		~ZygoZMI4104CClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		ZygoZMI4104CClass(string &);
		static ZygoZMI4104CClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	ZygoZMI4104C_H
