/*----- PROTECTED REGION ID(ZygoZMI4104CStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        ZygoZMI4104CStateMachine.cpp
//
// description : State machine file for the ZygoZMI4104C class
//
// project :     ZygoZMI4104C
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <ZygoZMI4104C.h>

/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::ZygoZMI4104CStateMachine.cpp

//================================================================
//  States   |  Description
//================================================================
//  ON       |  the device is connected and initialized
//  OFF      |  The device is not connected
//  STANDBY  |  the device is not properly initialized / initialization has failed
//  FAULT    |  There are some errors on the measurement board
//  INIT     |  device is being initialized


namespace ZygoZMI4104C_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_samplingFrequency_allowed()
 *	Description : Execution allowed for samplingFrequency attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_samplingFrequency_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for samplingFrequency attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::samplingFrequencyStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::samplingFrequencyStateAllowed_WRITE

	//	Not any excluded states for samplingFrequency attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::samplingFrequencyStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::samplingFrequencyStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis1LedState_allowed()
 *	Description : Execution allowed for axis1LedState attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis1LedState_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for axis1LedState attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis1LedStateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis1LedStateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis2LedState_allowed()
 *	Description : Execution allowed for axis2LedState attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis2LedState_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for axis2LedState attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis2LedStateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis2LedStateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis3LedState_allowed()
 *	Description : Execution allowed for axis3LedState attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis3LedState_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for axis3LedState attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis3LedStateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis3LedStateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis4LedState_allowed()
 *	Description : Execution allowed for axis4LedState attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis4LedState_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for axis4LedState attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis4LedStateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis4LedStateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_referenceAxisLedState_allowed()
 *	Description : Execution allowed for referenceAxisLedState attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_referenceAxisLedState_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for referenceAxisLedState attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::referenceAxisLedStateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::referenceAxisLedStateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_currentPrecision_allowed()
 *	Description : Execution allowed for currentPrecision attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_currentPrecision_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for currentPrecision attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::currentPrecisionStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::currentPrecisionStateAllowed_WRITE

	//	Not any excluded states for currentPrecision attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::currentPrecisionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::currentPrecisionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis1PositionValue_allowed()
 *	Description : Execution allowed for axis1PositionValue attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis1PositionValue_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for axis1PositionValue attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis1PositionValueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis1PositionValueStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis2PositionValue_allowed()
 *	Description : Execution allowed for axis2PositionValue attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis2PositionValue_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for axis2PositionValue attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis2PositionValueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis2PositionValueStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis3PositionValue_allowed()
 *	Description : Execution allowed for axis3PositionValue attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis3PositionValue_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for axis3PositionValue attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis3PositionValueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis3PositionValueStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis4PositionValue_allowed()
 *	Description : Execution allowed for axis4PositionValue attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis4PositionValue_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for axis4PositionValue attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis4PositionValueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis4PositionValueStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis1OpticalPowerValue_allowed()
 *	Description : Execution allowed for axis1OpticalPowerValue attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis1OpticalPowerValue_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for axis1OpticalPowerValue attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis1OpticalPowerValueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis1OpticalPowerValueStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis2OpticalPowerValue_allowed()
 *	Description : Execution allowed for axis2OpticalPowerValue attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis2OpticalPowerValue_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for axis2OpticalPowerValue attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis2OpticalPowerValueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis2OpticalPowerValueStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis3OpticalPowerValue_allowed()
 *	Description : Execution allowed for axis3OpticalPowerValue attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis3OpticalPowerValue_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for axis3OpticalPowerValue attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis3OpticalPowerValueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis3OpticalPowerValueStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis4OpticalPowerValue_allowed()
 *	Description : Execution allowed for axis4OpticalPowerValue attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis4OpticalPowerValue_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for axis4OpticalPowerValue attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis4OpticalPowerValueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis4OpticalPowerValueStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis1OffsetPositionValue_allowed()
 *	Description : Execution allowed for axis1OffsetPositionValue attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis1OffsetPositionValue_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for axis1OffsetPositionValue attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis1OffsetPositionValueStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis1OffsetPositionValueStateAllowed_WRITE

	//	Not any excluded states for axis1OffsetPositionValue attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis1OffsetPositionValueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis1OffsetPositionValueStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis2OffsetPositionValue_allowed()
 *	Description : Execution allowed for axis2OffsetPositionValue attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis2OffsetPositionValue_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for axis2OffsetPositionValue attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis2OffsetPositionValueStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis2OffsetPositionValueStateAllowed_WRITE

	//	Not any excluded states for axis2OffsetPositionValue attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis2OffsetPositionValueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis2OffsetPositionValueStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis3OffsetPositionValue_allowed()
 *	Description : Execution allowed for axis3OffsetPositionValue attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis3OffsetPositionValue_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for axis3OffsetPositionValue attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis3OffsetPositionValueStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis3OffsetPositionValueStateAllowed_WRITE

	//	Not any excluded states for axis3OffsetPositionValue attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis3OffsetPositionValueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis3OffsetPositionValueStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis4OffsetPositionValue_allowed()
 *	Description : Execution allowed for axis4OffsetPositionValue attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis4OffsetPositionValue_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for axis4OffsetPositionValue attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis4OffsetPositionValueStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis4OffsetPositionValueStateAllowed_WRITE

	//	Not any excluded states for axis4OffsetPositionValue attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis4OffsetPositionValueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis4OffsetPositionValueStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis1PresetPositionValue_allowed()
 *	Description : Execution allowed for axis1PresetPositionValue attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis1PresetPositionValue_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for axis1PresetPositionValue attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis1PresetPositionValueStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis1PresetPositionValueStateAllowed_WRITE

	//	Not any excluded states for axis1PresetPositionValue attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis1PresetPositionValueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis1PresetPositionValueStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis2PresetPositionValue_allowed()
 *	Description : Execution allowed for axis2PresetPositionValue attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis2PresetPositionValue_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for axis2PresetPositionValue attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis2PresetPositionValueStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis2PresetPositionValueStateAllowed_WRITE

	//	Not any excluded states for axis2PresetPositionValue attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis2PresetPositionValueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis2PresetPositionValueStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis3PresetPositionValue_allowed()
 *	Description : Execution allowed for axis3PresetPositionValue attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis3PresetPositionValue_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for axis3PresetPositionValue attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis3PresetPositionValueStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis3PresetPositionValueStateAllowed_WRITE

	//	Not any excluded states for axis3PresetPositionValue attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis3PresetPositionValueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis3PresetPositionValueStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis4PresetPositionValue_allowed()
 *	Description : Execution allowed for axis4PresetPositionValue attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis4PresetPositionValue_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for axis4PresetPositionValue attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis4PresetPositionValueStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis4PresetPositionValueStateAllowed_WRITE

	//	Not any excluded states for axis4PresetPositionValue attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis4PresetPositionValueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis4PresetPositionValueStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis1BiasMode_allowed()
 *	Description : Execution allowed for axis1BiasMode attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis1BiasMode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for axis1BiasMode attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis1BiasModeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis1BiasModeStateAllowed_WRITE

	//	Not any excluded states for axis1BiasMode attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis1BiasModeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis1BiasModeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis2BiasMode_allowed()
 *	Description : Execution allowed for axis2BiasMode attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis2BiasMode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for axis2BiasMode attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis2BiasModeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis2BiasModeStateAllowed_WRITE

	//	Not any excluded states for axis2BiasMode attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis2BiasModeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis2BiasModeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis3BiasMode_allowed()
 *	Description : Execution allowed for axis3BiasMode attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis3BiasMode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for axis3BiasMode attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis3BiasModeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis3BiasModeStateAllowed_WRITE

	//	Not any excluded states for axis3BiasMode attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis3BiasModeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis3BiasModeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axis4BiasMode_allowed()
 *	Description : Execution allowed for axis4BiasMode attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axis4BiasMode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for axis4BiasMode attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis4BiasModeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis4BiasModeStateAllowed_WRITE

	//	Not any excluded states for axis4BiasMode attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axis4BiasModeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axis4BiasModeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_interferometerConfiguration_allowed()
 *	Description : Execution allowed for interferometerConfiguration attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_interferometerConfiguration_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for interferometerConfiguration attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::interferometerConfigurationStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::interferometerConfigurationStateAllowed_WRITE

	//	Not any excluded states for interferometerConfiguration attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::interferometerConfigurationStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::interferometerConfigurationStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_sisFirmwareVersion_allowed()
 *	Description : Execution allowed for sisFirmwareVersion attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_sisFirmwareVersion_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for sisFirmwareVersion attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::sisFirmwareVersionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::sisFirmwareVersionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_sisBoardVersion_allowed()
 *	Description : Execution allowed for sisBoardVersion attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_sisBoardVersion_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for sisBoardVersion attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::sisBoardVersionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::sisBoardVersionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_zygoFirmwareVersion_allowed()
 *	Description : Execution allowed for zygoFirmwareVersion attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_zygoFirmwareVersion_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for zygoFirmwareVersion attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::zygoFirmwareVersionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::zygoFirmwareVersionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_zygoBoardVersion_allowed()
 *	Description : Execution allowed for zygoBoardVersion attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_zygoBoardVersion_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for zygoBoardVersion attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::zygoBoardVersionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::zygoBoardVersionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_zygoSerialNumber_allowed()
 *	Description : Execution allowed for zygoSerialNumber attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_zygoSerialNumber_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for zygoSerialNumber attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::zygoSerialNumberStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::zygoSerialNumberStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_continuousSamplingAxes_allowed()
 *	Description : Execution allowed for continuousSamplingAxes attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_continuousSamplingAxes_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for continuousSamplingAxes attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::continuousSamplingAxesStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::continuousSamplingAxesStateAllowed_WRITE

	//	Not any excluded states for continuousSamplingAxes attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::continuousSamplingAxesStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::continuousSamplingAxesStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_continuousSamplingSize_allowed()
 *	Description : Execution allowed for continuousSamplingSize attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_continuousSamplingSize_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for continuousSamplingSize attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::continuousSamplingSizeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::continuousSamplingSizeStateAllowed_WRITE

	//	Not any excluded states for continuousSamplingSize attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::continuousSamplingSizeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::continuousSamplingSizeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_cecAxes_allowed()
 *	Description : Execution allowed for cecAxes attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_cecAxes_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for cecAxes attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::cecAxesStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::cecAxesStateAllowed_WRITE

	//	Not any excluded states for cecAxes attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::cecAxesStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::cecAxesStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_continuousScanPositionMeanValue_allowed()
 *	Description : Execution allowed for continuousScanPositionMeanValue attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_continuousScanPositionMeanValue_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for continuousScanPositionMeanValue attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::continuousScanPositionMeanValueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::continuousScanPositionMeanValueStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_continuousScanPositionStdDev_allowed()
 *	Description : Execution allowed for continuousScanPositionStdDev attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_continuousScanPositionStdDev_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for continuousScanPositionStdDev attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::continuousScanPositionStdDevStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::continuousScanPositionStdDevStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_fifoMode_allowed()
 *	Description : Execution allowed for fifoMode attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_fifoMode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for fifoMode attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::fifoModeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::fifoModeStateAllowed_WRITE

	//	Not any excluded states for fifoMode attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::fifoModeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::fifoModeStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_ResetMeasurementAxis_allowed()
 *	Description : Execution allowed for ResetMeasurementAxis attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_ResetMeasurementAxis_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ResetMeasurementAxis command.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::ResetMeasurementAxisStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::ResetMeasurementAxisStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_StartContinuousAcquisition_allowed()
 *	Description : Execution allowed for StartContinuousAcquisition attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_StartContinuousAcquisition_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for StartContinuousAcquisition command.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::StartContinuousAcquisitionStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::StartContinuousAcquisitionStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_StopContinnuousAcquisition_allowed()
 *	Description : Execution allowed for StopContinnuousAcquisition attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_StopContinnuousAcquisition_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for StopContinnuousAcquisition command.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::StopContinnuousAcquisitionStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::StopContinnuousAcquisitionStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_EnableCyclicErrorCompensation_allowed()
 *	Description : Execution allowed for EnableCyclicErrorCompensation attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_EnableCyclicErrorCompensation_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for EnableCyclicErrorCompensation command.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::EnableCyclicErrorCompensationStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::EnableCyclicErrorCompensationStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_DisableCyclicErrorCompensation_allowed()
 *	Description : Execution allowed for DisableCyclicErrorCompensation attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_DisableCyclicErrorCompensation_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for DisableCyclicErrorCompensation command.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::DisableCyclicErrorCompensationStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::DisableCyclicErrorCompensationStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_ResetMeasurementSystem_allowed()
 *	Description : Execution allowed for ResetMeasurementSystem attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_ResetMeasurementSystem_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ResetMeasurementSystem command.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::ResetMeasurementSystemStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::ResetMeasurementSystemStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(ZygoZMI4104C::ZygoZMI4104CStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::ZygoZMI4104CStateAllowed.AdditionalMethods

}	//	End of namespace
