/*----- PROTECTED REGION ID(ZygoZMI4104CStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        ZygoZMI4104CStateMachine.cpp
//
// description : State machine file for the ZygoZMI4104C class
//
// project :     zygoZMI4104C
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <ZygoZMI4104C.h>

/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::ZygoZMI4104CStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  FAULT   |  the device is not properly initialized or some errors are present on the measurement board
//  ON      |  the device is present and well initialised
//  OFF     |  the device is absent or can not be initialized


namespace ZygoZMI4104C_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_baseAddress_allowed()
 *	Description : Execution allowed for baseAddress attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_baseAddress_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for baseAddress attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::baseAddressStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::baseAddressStateAllowed_WRITE

	//	Not any excluded states for baseAddress attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::baseAddressStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::baseAddressStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_interferometerType_allowed()
 *	Description : Execution allowed for interferometerType attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_interferometerType_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for interferometerType attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::interferometerTypeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::interferometerTypeStateAllowed_WRITE

	//	Not any excluded states for interferometerType attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::interferometerTypeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::interferometerTypeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_positionPrecision_allowed()
 *	Description : Execution allowed for positionPrecision attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_positionPrecision_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for positionPrecision attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::positionPrecisionStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::positionPrecisionStateAllowed_WRITE

	//	Not any excluded states for positionPrecision attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::positionPrecisionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::positionPrecisionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_sampleSourceClock_allowed()
 *	Description : Execution allowed for sampleSourceClock attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_sampleSourceClock_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for sampleSourceClock attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::sampleSourceClockStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::sampleSourceClockStateAllowed_WRITE

	//	Not any excluded states for sampleSourceClock attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::sampleSourceClockStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::sampleSourceClockStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_resetSourceClock_allowed()
 *	Description : Execution allowed for resetSourceClock attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_resetSourceClock_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for resetSourceClock attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::resetSourceClockStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::resetSourceClockStateAllowed_WRITE

	//	Not any excluded states for resetSourceClock attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::resetSourceClockStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::resetSourceClockStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_samplingFrequency_allowed()
 *	Description : Execution allowed for samplingFrequency attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_samplingFrequency_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for samplingFrequency attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::samplingFrequencyStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::samplingFrequencyStateAllowed_WRITE

	//	Not any excluded states for samplingFrequency attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::samplingFrequencyStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::samplingFrequencyStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_biasMode_allowed()
 *	Description : Execution allowed for biasMode attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_biasMode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for biasMode attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::biasModeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::biasModeStateAllowed_WRITE

	//	Not any excluded states for biasMode attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::biasModeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::biasModeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_cecState_allowed()
 *	Description : Execution allowed for cecState attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_cecState_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for cecState attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::cecStateStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::cecStateStateAllowed_WRITE

	//	Not any excluded states for cecState attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::cecStateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::cecStateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_continuousScanIntegrationTime_allowed()
 *	Description : Execution allowed for continuousScanIntegrationTime attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_continuousScanIntegrationTime_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for continuousScanIntegrationTime attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::continuousScanIntegrationTimeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::continuousScanIntegrationTimeStateAllowed_WRITE

	//	Not any excluded states for continuousScanIntegrationTime attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::continuousScanIntegrationTimeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::continuousScanIntegrationTimeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_continuousScanFrequency_allowed()
 *	Description : Execution allowed for continuousScanFrequency attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_continuousScanFrequency_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for continuousScanFrequency attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::continuousScanFrequencyStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::continuousScanFrequencyStateAllowed_WRITE

	//	Not any excluded states for continuousScanFrequency attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::continuousScanFrequencyStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::continuousScanFrequencyStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_continuousScanSize_allowed()
 *	Description : Execution allowed for continuousScanSize attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_continuousScanSize_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for continuousScanSize attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::continuousScanSizeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::continuousScanSizeStateAllowed_WRITE

	//	Not any excluded states for continuousScanSize attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::continuousScanSizeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::continuousScanSizeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axisPositions_allowed()
 *	Description : Execution allowed for axisPositions attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axisPositions_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for axisPositions attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axisPositionsStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axisPositionsStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axisOpticalPowers_allowed()
 *	Description : Execution allowed for axisOpticalPowers attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axisOpticalPowers_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for axisOpticalPowers attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axisOpticalPowersStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axisOpticalPowersStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axisVelocities_allowed()
 *	Description : Execution allowed for axisVelocities attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axisVelocities_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for axisVelocities attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axisVelocitiesStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axisVelocitiesStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axisPositionOffsets_allowed()
 *	Description : Execution allowed for axisPositionOffsets attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axisPositionOffsets_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for axisPositionOffsets attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axisPositionOffsetsStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axisPositionOffsetsStateAllowed_WRITE

	//	Not any excluded states for axisPositionOffsets attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axisPositionOffsetsStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axisPositionOffsetsStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_axisPositionPresets_allowed()
 *	Description : Execution allowed for axisPositionPresets attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_axisPositionPresets_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for axisPositionPresets attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axisPositionPresetsStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axisPositionPresetsStateAllowed_WRITE

	//	Not any excluded states for axisPositionPresets attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::axisPositionPresetsStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::axisPositionPresetsStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_ledsStatus_allowed()
 *	Description : Execution allowed for ledsStatus attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_ledsStatus_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for ledsStatus attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::ledsStatusStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::ledsStatusStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_continuousScanAxisTab_allowed()
 *	Description : Execution allowed for continuousScanAxisTab attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_continuousScanAxisTab_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for continuousScanAxisTab attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::continuousScanAxisTabStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::continuousScanAxisTabStateAllowed_WRITE

	//	Not any excluded states for continuousScanAxisTab attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::continuousScanAxisTabStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::continuousScanAxisTabStateAllowed_READ
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_ReadPosition_allowed()
 *	Description : Execution allowed for ReadPosition attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_ReadPosition_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ReadPosition command.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::ReadPositionStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::ReadPositionStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_ReadVelocity_allowed()
 *	Description : Execution allowed for ReadVelocity attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_ReadVelocity_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ReadVelocity command.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::ReadVelocityStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::ReadVelocityStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_ReadOpticalPower_allowed()
 *	Description : Execution allowed for ReadOpticalPower attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_ReadOpticalPower_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ReadOpticalPower command.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::ReadOpticalPowerStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::ReadOpticalPowerStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_ResetAxis_allowed()
 *	Description : Execution allowed for ResetAxis attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_ResetAxis_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ResetAxis command.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::ResetAxisStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::ResetAxisStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_InitializeZMISystem_allowed()
 *	Description : Execution allowed for InitializeZMISystem attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_InitializeZMISystem_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for InitializeZMISystem command.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::InitializeZMISystemStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::InitializeZMISystemStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_EnableCyclicErrorCorrection_allowed()
 *	Description : Execution allowed for EnableCyclicErrorCorrection attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_EnableCyclicErrorCorrection_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for EnableCyclicErrorCorrection command.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::EnableCyclicErrorCorrectionStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::EnableCyclicErrorCorrectionStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_DisableCyclicErrorCorrection_allowed()
 *	Description : Execution allowed for DisableCyclicErrorCorrection attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_DisableCyclicErrorCorrection_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for DisableCyclicErrorCorrection command.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::DisableCyclicErrorCorrectionStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::DisableCyclicErrorCorrectionStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI4104C::is_StartContinuousScan_allowed()
 *	Description : Execution allowed for StartContinuousScan attribute
 */
//--------------------------------------------------------
bool ZygoZMI4104C::is_StartContinuousScan_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for StartContinuousScan command.
	/*----- PROTECTED REGION ID(ZygoZMI4104C::StartContinuousScanStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI4104C::StartContinuousScanStateAllowed
	return true;
}

}	//	End of namespace
