/*----- PROTECTED REGION ID(ZygoZMI.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        ZygoZMI.cpp
//
// description : C++ source for the ZygoZMI class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               ZygoZMI are implemented in this file.
//
// project :     zygoZMI4104c
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <ZygoZMI.h>
#include <ZygoZMIClass.h>

/*----- PROTECTED REGION END -----*/	//	ZygoZMI.cpp

/**
 *  ZygoZMI class description:
 *    Zygo interferometer tango device`s which use a zmi4104c measurement board with a SIS VME/PCIe gateway.
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name                |  Method name
//================================================================
//  State                       |  Inherited (no method)
//  Status                      |  Inherited (no method)
//  Start                       |  start
//  Stop                        |  stop
//  updatePosition              |  update_position
//  startContinuousAcquisition  |  start_continuous_acquisition
//  reset                       |  reset
//================================================================

//================================================================
//  Attributes managed are:
//================================================================
//  axis1Position           |  Tango::DevDouble	Scalar
//  axis1State              |  Tango::DevEnum	Scalar
//  boardVersion            |  Tango::DevString	Scalar
//  boardFirmwareVersion    |  Tango::DevString	Scalar
//  gatewayBoardVersion     |  Tango::DevString	Scalar
//  gatewayFirmwareVersion  |  Tango::DevString	Scalar
//  flyscanAxisNbr          |  Tango::DevUChar	Scalar
//  flyscanFreq             |  Tango::DevDouble	Scalar
//  flyscanTime             |  Tango::DevDouble	Scalar
//================================================================

namespace ZygoZMI_ns
{
/*----- PROTECTED REGION ID(ZygoZMI::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	ZygoZMI::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI::ZygoZMI()
 *	Description : Constructors for a Tango device
 *                implementing the classZygoZMI
 */
//--------------------------------------------------------
ZygoZMI::ZygoZMI(Tango::DeviceClass *cl, string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(ZygoZMI::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::constructor_1
}
//--------------------------------------------------------
ZygoZMI::ZygoZMI(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(ZygoZMI::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::constructor_2
}
//--------------------------------------------------------
ZygoZMI::ZygoZMI(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(ZygoZMI::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void ZygoZMI::delete_device()
{
	DEBUG_STREAM << "ZygoZMI::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(ZygoZMI::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::delete_device
	delete[] attr_axis1Position_read;
	delete[] attr_axis1State_read;
	delete[] attr_boardVersion_read;
	delete[] attr_boardFirmwareVersion_read;
	delete[] attr_gatewayBoardVersion_read;
	delete[] attr_gatewayFirmwareVersion_read;
	delete[] attr_flyscanAxisNbr_read;
	delete[] attr_flyscanFreq_read;
	delete[] attr_flyscanTime_read;
	//
	delete[] position;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void ZygoZMI::init_device()
{
	DEBUG_STREAM << "ZygoZMI::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(ZygoZMI::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::init_device_before
	
	//	No device property to be read from database
	
	attr_axis1Position_read = new Tango::DevDouble[1];
	attr_axis1State_read = new axis1StateEnum[1];
	attr_boardVersion_read = new Tango::DevString[1];
	attr_boardFirmwareVersion_read = new Tango::DevString[1];
	attr_gatewayBoardVersion_read = new Tango::DevString[1];
	attr_gatewayFirmwareVersion_read = new Tango::DevString[1];
	attr_flyscanAxisNbr_read = new Tango::DevUChar[1];
	attr_flyscanFreq_read = new Tango::DevDouble[1];
	attr_flyscanTime_read = new Tango::DevDouble[1];
	position = new double[4];
	/*	
	attr_boardVersion_read = malloc(sizeof(ZYGO_BOARD_VERSION));
	attr_boardVersion_read = memset(attr_boardVersion_read, 0, sizeof(attr_boardVersion_read));
	
	attr_boardFirmwareVersion_read = malloc(sizeof(ZYGO_FIRMWARE_VERSION));
	attr_boardFirmwareVersion_read = memset(attr_boardFirmwareVersion_read, 0, sizeof(attr_boardFirmwareVersion_read));
	
	attr_gatewayBoardVersion_read = malloc(sizeof(PCI_VME_GATEWAY_BOARD_VERSION));
	attr_gatewayBoardVersion_read = memset(attr_gatewayBoardVersion_read, 0, sizeof(attr_gatewayBoardVersion_read));
	
	attr_gatewayFirmwareVersion_read = malloc(sizeof(PCI_VME_GATEWAY_FIRMWARE_VERSION));
	attr_gatewayFirmwareVersion_read = memset(attr_gatewayFirmwareVersion_read, 0, sizeof(attr_gatewayFirmwareVersion_read));
	*/
	/*----- PROTECTED REGION ID(ZygoZMI::init_device) ENABLED START -----*/
	
	//	Initialize device
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::init_device
}


//--------------------------------------------------------
/**
 *	Method      : ZygoZMI::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void ZygoZMI::always_executed_hook()
{
	DEBUG_STREAM << "ZygoZMI::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(ZygoZMI::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void ZygoZMI::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "ZygoZMI::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(ZygoZMI::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::read_attr_hardware
}
//--------------------------------------------------------
/**
 *	Method      : ZygoZMI::write_attr_hardware()
 *	Description : Hardware writing for attributes
 */
//--------------------------------------------------------
void ZygoZMI::write_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "ZygoZMI::write_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(ZygoZMI::write_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::write_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute axis1Position related method
 *	Description: measured position on axis 1
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void ZygoZMI::read_axis1Position(Tango::Attribute &attr)
{
	DEBUG_STREAM << "ZygoZMI::read_axis1Position(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(ZygoZMI::read_axis1Position) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_axis1Position_read);
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::read_axis1Position
}
//--------------------------------------------------------
/**
 *	Read attribute axis1State related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (axis1StateEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void ZygoZMI::read_axis1State(Tango::Attribute &attr)
{
	DEBUG_STREAM << "ZygoZMI::read_axis1State(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(ZygoZMI::read_axis1State) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_axis1State_read);
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::read_axis1State
}
//--------------------------------------------------------
/**
 *	Read attribute boardVersion related method
 *	Description: 
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void ZygoZMI::read_boardVersion(Tango::Attribute &attr)
{
	DEBUG_STREAM << "ZygoZMI::read_boardVersion(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(ZygoZMI::read_boardVersion) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_boardVersion_read);
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::read_boardVersion
}
//--------------------------------------------------------
/**
 *	Read attribute boardFirmwareVersion related method
 *	Description: 
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void ZygoZMI::read_boardFirmwareVersion(Tango::Attribute &attr)
{
	DEBUG_STREAM << "ZygoZMI::read_boardFirmwareVersion(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(ZygoZMI::read_boardFirmwareVersion) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_boardFirmwareVersion_read);
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::read_boardFirmwareVersion
}
//--------------------------------------------------------
/**
 *	Read attribute gatewayBoardVersion related method
 *	Description: 
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void ZygoZMI::read_gatewayBoardVersion(Tango::Attribute &attr)
{
	DEBUG_STREAM << "ZygoZMI::read_gatewayBoardVersion(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(ZygoZMI::read_gatewayBoardVersion) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_gatewayBoardVersion_read);
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::read_gatewayBoardVersion
}
//--------------------------------------------------------
/**
 *	Read attribute gatewayFirmwareVersion related method
 *	Description: 
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void ZygoZMI::read_gatewayFirmwareVersion(Tango::Attribute &attr)
{
	DEBUG_STREAM << "ZygoZMI::read_gatewayFirmwareVersion(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(ZygoZMI::read_gatewayFirmwareVersion) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_gatewayFirmwareVersion_read);
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::read_gatewayFirmwareVersion
}
//--------------------------------------------------------
/**
 *	Read attribute flyscanAxisNbr related method
 *	Description: 
 *
 *	Data type:	Tango::DevUChar
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void ZygoZMI::read_flyscanAxisNbr(Tango::Attribute &attr)
{
	DEBUG_STREAM << "ZygoZMI::read_flyscanAxisNbr(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(ZygoZMI::read_flyscanAxisNbr) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_flyscanAxisNbr_read);
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::read_flyscanAxisNbr
}
//--------------------------------------------------------
/**
 *	Write attribute flyscanAxisNbr related method
 *	Description: 
 *
 *	Data type:	Tango::DevUChar
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void ZygoZMI::write_flyscanAxisNbr(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "ZygoZMI::write_flyscanAxisNbr(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevUChar	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(ZygoZMI::write_flyscanAxisNbr) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::write_flyscanAxisNbr
}
//--------------------------------------------------------
/**
 *	Read attribute flyscanFreq related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void ZygoZMI::read_flyscanFreq(Tango::Attribute &attr)
{
	DEBUG_STREAM << "ZygoZMI::read_flyscanFreq(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(ZygoZMI::read_flyscanFreq) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_flyscanFreq_read);
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::read_flyscanFreq
}
//--------------------------------------------------------
/**
 *	Write attribute flyscanFreq related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void ZygoZMI::write_flyscanFreq(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "ZygoZMI::write_flyscanFreq(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(ZygoZMI::write_flyscanFreq) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::write_flyscanFreq
}
//--------------------------------------------------------
/**
 *	Read attribute flyscanTime related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void ZygoZMI::read_flyscanTime(Tango::Attribute &attr)
{
	DEBUG_STREAM << "ZygoZMI::read_flyscanTime(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(ZygoZMI::read_flyscanTime) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_flyscanTime_read);
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::read_flyscanTime
}
//--------------------------------------------------------
/**
 *	Write attribute flyscanTime related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void ZygoZMI::write_flyscanTime(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "ZygoZMI::write_flyscanTime(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(ZygoZMI::write_flyscanTime) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::write_flyscanTime
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void ZygoZMI::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(ZygoZMI::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command Start related method
 *	Description: Start the measurment system
 *
 */
//--------------------------------------------------------
void ZygoZMI::start()
{
	DEBUG_STREAM << "ZygoZMI::Start()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(ZygoZMI::start) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::start
}
//--------------------------------------------------------
/**
 *	Command Stop related method
 *	Description: Stop tha continuous acquisition
 *
 */
//--------------------------------------------------------
void ZygoZMI::stop()
{
	DEBUG_STREAM << "ZygoZMI::Stop()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(ZygoZMI::stop) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::stop
}
//--------------------------------------------------------
/**
 *	Command updatePosition related method
 *	Description: refresh the position on the given axis
 *
 *	@param argin 
 */
//--------------------------------------------------------
void ZygoZMI::update_position(Tango::DevUShort argin)
{
	DEBUG_STREAM << "ZygoZMI::updatePosition()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(ZygoZMI::update_position) ENABLED START -----*/
    ReadSamplePosition37_ForAllAxis( position);
	
	attr_axis1Position_read = postion[0];
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::update_position
}
//--------------------------------------------------------
/**
 *	Command startContinuousAcquisition related method
 *	Description: Starts the continuous acquisition using values store in attributes flyscanAxisNbr, flyscanFreq and flyscanTime
 *
 */
//--------------------------------------------------------
void ZygoZMI::start_continuous_acquisition()
{
	DEBUG_STREAM << "ZygoZMI::startContinuousAcquisition()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(ZygoZMI::start_continuous_acquisition) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::start_continuous_acquisition
}
//--------------------------------------------------------
/**
 *	Command reset related method
 *	Description: reset all the VME system(including gateway boards)
 *
 */
//--------------------------------------------------------
void ZygoZMI::reset()
{
	DEBUG_STREAM << "ZygoZMI::reset()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(ZygoZMI::reset) ENABLED START -----*/
	
	//	Add your own code
    BIAS_MODE bias_mode = BIAS_CONSTANT_VOLT_MODE;
	if(initSISboards( )!= RET_SUCCESS) FATAL("Failed to initialize SIS boards\n");
    //Sleep(10);
    if(initZMIboards( ) != RET_SUCCESS) FATAL("Failed to initialize ZMI board\n");
    //ui->pushButton_11->setEnabled(false);
    if(initAxis(  bias_mode) != RET_SUCCESS) FATAL("Failed to initialize axis\n");
    EnableDoublePassInterferometer();

	scopy_s(attr_boardVersion_read, PCI_VME_GATEWAY_BOARD_VERSION, sizeof(attr_boardVersion_read));
	/*
	*attr_boardFirmwareVersion_read;
	*attr_gatewayBoardVersion_read;
	*attr_gatewayFirmwareVersion_read;
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::reset
}
//--------------------------------------------------------
/**
 *	Method      : ZygoZMI::add_dynamic_commands()
 *	Description : Create the dynamic commands if any
 *                for specified device.
 */
//--------------------------------------------------------
void ZygoZMI::add_dynamic_commands()
{
	/*----- PROTECTED REGION ID(ZygoZMI::add_dynamic_commands) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic commands if any
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::add_dynamic_commands
}

/*----- PROTECTED REGION ID(ZygoZMI::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	ZygoZMI::namespace_ending
} //	namespace
