/*----- PROTECTED REGION ID(ZygoZMIClass.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        ZygoZMIClass.cpp
//
// description : C++ source for the ZygoZMIClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the ZygoZMI once per process.
//
// project :     zygoZMI4104c
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <ZygoZMIClass.h>

/*----- PROTECTED REGION END -----*/	//	ZygoZMIClass.cpp

//-------------------------------------------------------------------
/**
 *	Create ZygoZMIClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_ZygoZMI_class(const char *name) {
		return ZygoZMI_ns::ZygoZMIClass::init(name);
	}
}

namespace ZygoZMI_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
ZygoZMIClass *ZygoZMIClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		ZygoZMIClass::ZygoZMIClass(string &s)
 * description : 	constructor for the ZygoZMIClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
ZygoZMIClass::ZygoZMIClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering ZygoZMIClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(ZygoZMIClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMIClass::constructor

	cout2 << "Leaving ZygoZMIClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		ZygoZMIClass::~ZygoZMIClass()
 * description : 	destructor for the ZygoZMIClass
 */
//--------------------------------------------------------
ZygoZMIClass::~ZygoZMIClass()
{
	/*----- PROTECTED REGION ID(ZygoZMIClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMIClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		ZygoZMIClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
ZygoZMIClass *ZygoZMIClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new ZygoZMIClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		ZygoZMIClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
ZygoZMIClass *ZygoZMIClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		StartClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *StartClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "StartClass::execute(): arrived" << endl;
	((static_cast<ZygoZMI *>(device))->start());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		StopClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *StopClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "StopClass::execute(): arrived" << endl;
	((static_cast<ZygoZMI *>(device))->stop());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		updatePositionClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *updatePositionClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "updatePositionClass::execute(): arrived" << endl;
	Tango::DevUShort argin;
	extract(in_any, argin);
	((static_cast<ZygoZMI *>(device))->update_position(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		startContinuousAcquisitionClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *startContinuousAcquisitionClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "startContinuousAcquisitionClass::execute(): arrived" << endl;
	((static_cast<ZygoZMI *>(device))->start_continuous_acquisition());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		resetClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *resetClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "resetClass::execute(): arrived" << endl;
	((static_cast<ZygoZMI *>(device))->reset());
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : ZygoZMIClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum ZygoZMIClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMIClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum ZygoZMIClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMIClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum ZygoZMIClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : ZygoZMIClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void ZygoZMIClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMIClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void ZygoZMIClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("zygoZMI4104c");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("Zygo interferometer tango device`s which use a zmi4104c measurement board with a SIS VME/PCIe gateway.");
	description << str_desc;
	data.push_back(description);

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : ZygoZMIClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void ZygoZMIClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(ZygoZMIClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMIClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new ZygoZMI(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		ZygoZMI *dev = static_cast<ZygoZMI *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(ZygoZMIClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMIClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : ZygoZMIClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void ZygoZMIClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(ZygoZMIClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMIClass::attribute_factory_before
	//	Attribute : axis1Position
	axis1PositionAttrib	*axis1position = new axis1PositionAttrib();
	Tango::UserDefaultAttrProp	axis1position_prop;
	axis1position_prop.set_description("measured position on axis 1");
	//	label	not set for axis1Position
	axis1position_prop.set_unit("nm");
	//	standard_unit	not set for axis1Position
	//	display_unit	not set for axis1Position
	//	format	not set for axis1Position
	//	max_value	not set for axis1Position
	//	min_value	not set for axis1Position
	//	max_alarm	not set for axis1Position
	//	min_alarm	not set for axis1Position
	//	max_warning	not set for axis1Position
	//	min_warning	not set for axis1Position
	//	delta_t	not set for axis1Position
	//	delta_val	not set for axis1Position
	
	axis1position->set_default_properties(axis1position_prop);
	//	Not Polled
	axis1position->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(axis1position);

	//	Attribute : axis1State
	axis1StateAttrib	*axis1state = new axis1StateAttrib();
	Tango::UserDefaultAttrProp	axis1state_prop;
	//	description	not set for axis1State
	//	label	not set for axis1State
	//	unit	not set for axis1State
	//	standard_unit	not set for axis1State
	//	display_unit	not set for axis1State
	//	format	not set for axis1State
	//	max_value	not set for axis1State
	//	min_value	not set for axis1State
	//	max_alarm	not set for axis1State
	//	min_alarm	not set for axis1State
	//	max_warning	not set for axis1State
	//	min_warning	not set for axis1State
	//	delta_t	not set for axis1State
	//	delta_val	not set for axis1State
	
	{
		vector<string> labels;
		labels.push_back("NOSIGNAL");
		labels.push_back("ERROR");
		labels.push_back("OK");
		axis1state_prop.set_enum_labels(labels);
	}
	axis1state->set_default_properties(axis1state_prop);
	//	Not Polled
	axis1state->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(axis1state);

	//	Attribute : boardVersion
	boardVersionAttrib	*boardversion = new boardVersionAttrib();
	Tango::UserDefaultAttrProp	boardversion_prop;
	//	description	not set for boardVersion
	//	label	not set for boardVersion
	//	unit	not set for boardVersion
	//	standard_unit	not set for boardVersion
	//	display_unit	not set for boardVersion
	//	format	not set for boardVersion
	//	max_value	not set for boardVersion
	//	min_value	not set for boardVersion
	//	max_alarm	not set for boardVersion
	//	min_alarm	not set for boardVersion
	//	max_warning	not set for boardVersion
	//	min_warning	not set for boardVersion
	//	delta_t	not set for boardVersion
	//	delta_val	not set for boardVersion
	
	boardversion->set_default_properties(boardversion_prop);
	//	Not Polled
	boardversion->set_disp_level(Tango::EXPERT);
	//	Not Memorized
	att_list.push_back(boardversion);

	//	Attribute : boardFirmwareVersion
	boardFirmwareVersionAttrib	*boardfirmwareversion = new boardFirmwareVersionAttrib();
	Tango::UserDefaultAttrProp	boardfirmwareversion_prop;
	//	description	not set for boardFirmwareVersion
	//	label	not set for boardFirmwareVersion
	//	unit	not set for boardFirmwareVersion
	//	standard_unit	not set for boardFirmwareVersion
	//	display_unit	not set for boardFirmwareVersion
	//	format	not set for boardFirmwareVersion
	//	max_value	not set for boardFirmwareVersion
	//	min_value	not set for boardFirmwareVersion
	//	max_alarm	not set for boardFirmwareVersion
	//	min_alarm	not set for boardFirmwareVersion
	//	max_warning	not set for boardFirmwareVersion
	//	min_warning	not set for boardFirmwareVersion
	//	delta_t	not set for boardFirmwareVersion
	//	delta_val	not set for boardFirmwareVersion
	
	boardfirmwareversion->set_default_properties(boardfirmwareversion_prop);
	//	Not Polled
	boardfirmwareversion->set_disp_level(Tango::EXPERT);
	//	Not Memorized
	att_list.push_back(boardfirmwareversion);

	//	Attribute : gatewayBoardVersion
	gatewayBoardVersionAttrib	*gatewayboardversion = new gatewayBoardVersionAttrib();
	Tango::UserDefaultAttrProp	gatewayboardversion_prop;
	//	description	not set for gatewayBoardVersion
	//	label	not set for gatewayBoardVersion
	//	unit	not set for gatewayBoardVersion
	//	standard_unit	not set for gatewayBoardVersion
	//	display_unit	not set for gatewayBoardVersion
	//	format	not set for gatewayBoardVersion
	//	max_value	not set for gatewayBoardVersion
	//	min_value	not set for gatewayBoardVersion
	//	max_alarm	not set for gatewayBoardVersion
	//	min_alarm	not set for gatewayBoardVersion
	//	max_warning	not set for gatewayBoardVersion
	//	min_warning	not set for gatewayBoardVersion
	//	delta_t	not set for gatewayBoardVersion
	//	delta_val	not set for gatewayBoardVersion
	
	gatewayboardversion->set_default_properties(gatewayboardversion_prop);
	//	Not Polled
	gatewayboardversion->set_disp_level(Tango::EXPERT);
	//	Not Memorized
	att_list.push_back(gatewayboardversion);

	//	Attribute : gatewayFirmwareVersion
	gatewayFirmwareVersionAttrib	*gatewayfirmwareversion = new gatewayFirmwareVersionAttrib();
	Tango::UserDefaultAttrProp	gatewayfirmwareversion_prop;
	//	description	not set for gatewayFirmwareVersion
	//	label	not set for gatewayFirmwareVersion
	//	unit	not set for gatewayFirmwareVersion
	//	standard_unit	not set for gatewayFirmwareVersion
	//	display_unit	not set for gatewayFirmwareVersion
	//	format	not set for gatewayFirmwareVersion
	//	max_value	not set for gatewayFirmwareVersion
	//	min_value	not set for gatewayFirmwareVersion
	//	max_alarm	not set for gatewayFirmwareVersion
	//	min_alarm	not set for gatewayFirmwareVersion
	//	max_warning	not set for gatewayFirmwareVersion
	//	min_warning	not set for gatewayFirmwareVersion
	//	delta_t	not set for gatewayFirmwareVersion
	//	delta_val	not set for gatewayFirmwareVersion
	
	gatewayfirmwareversion->set_default_properties(gatewayfirmwareversion_prop);
	//	Not Polled
	gatewayfirmwareversion->set_disp_level(Tango::EXPERT);
	//	Not Memorized
	att_list.push_back(gatewayfirmwareversion);

	//	Attribute : flyscanAxisNbr
	flyscanAxisNbrAttrib	*flyscanaxisnbr = new flyscanAxisNbrAttrib();
	Tango::UserDefaultAttrProp	flyscanaxisnbr_prop;
	//	description	not set for flyscanAxisNbr
	//	label	not set for flyscanAxisNbr
	//	unit	not set for flyscanAxisNbr
	//	standard_unit	not set for flyscanAxisNbr
	//	display_unit	not set for flyscanAxisNbr
	//	format	not set for flyscanAxisNbr
	//	max_value	not set for flyscanAxisNbr
	//	min_value	not set for flyscanAxisNbr
	//	max_alarm	not set for flyscanAxisNbr
	//	min_alarm	not set for flyscanAxisNbr
	//	max_warning	not set for flyscanAxisNbr
	//	min_warning	not set for flyscanAxisNbr
	//	delta_t	not set for flyscanAxisNbr
	//	delta_val	not set for flyscanAxisNbr
	
	flyscanaxisnbr->set_default_properties(flyscanaxisnbr_prop);
	//	Not Polled
	flyscanaxisnbr->set_disp_level(Tango::OPERATOR);
	flyscanaxisnbr->set_memorized();
	flyscanaxisnbr->set_memorized_init(false);
	att_list.push_back(flyscanaxisnbr);

	//	Attribute : flyscanFreq
	flyscanFreqAttrib	*flyscanfreq = new flyscanFreqAttrib();
	Tango::UserDefaultAttrProp	flyscanfreq_prop;
	//	description	not set for flyscanFreq
	//	label	not set for flyscanFreq
	//	unit	not set for flyscanFreq
	//	standard_unit	not set for flyscanFreq
	//	display_unit	not set for flyscanFreq
	//	format	not set for flyscanFreq
	//	max_value	not set for flyscanFreq
	//	min_value	not set for flyscanFreq
	//	max_alarm	not set for flyscanFreq
	//	min_alarm	not set for flyscanFreq
	//	max_warning	not set for flyscanFreq
	//	min_warning	not set for flyscanFreq
	//	delta_t	not set for flyscanFreq
	//	delta_val	not set for flyscanFreq
	
	flyscanfreq->set_default_properties(flyscanfreq_prop);
	//	Not Polled
	flyscanfreq->set_disp_level(Tango::OPERATOR);
	flyscanfreq->set_memorized();
	flyscanfreq->set_memorized_init(false);
	att_list.push_back(flyscanfreq);

	//	Attribute : flyscanTime
	flyscanTimeAttrib	*flyscantime = new flyscanTimeAttrib();
	Tango::UserDefaultAttrProp	flyscantime_prop;
	//	description	not set for flyscanTime
	//	label	not set for flyscanTime
	//	unit	not set for flyscanTime
	//	standard_unit	not set for flyscanTime
	//	display_unit	not set for flyscanTime
	//	format	not set for flyscanTime
	//	max_value	not set for flyscanTime
	//	min_value	not set for flyscanTime
	//	max_alarm	not set for flyscanTime
	//	min_alarm	not set for flyscanTime
	//	max_warning	not set for flyscanTime
	//	min_warning	not set for flyscanTime
	//	delta_t	not set for flyscanTime
	//	delta_val	not set for flyscanTime
	
	flyscantime->set_default_properties(flyscantime_prop);
	//	Not Polled
	flyscantime->set_disp_level(Tango::OPERATOR);
	flyscantime->set_memorized();
	flyscantime->set_memorized_init(false);
	att_list.push_back(flyscantime);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(ZygoZMIClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMIClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : ZygoZMIClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void ZygoZMIClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(ZygoZMIClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMIClass::pipe_factory_before
	/*----- PROTECTED REGION ID(ZygoZMIClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMIClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : ZygoZMIClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void ZygoZMIClass::command_factory()
{
	/*----- PROTECTED REGION ID(ZygoZMIClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMIClass::command_factory_before


	//	Command Start
	StartClass	*pStartCmd =
		new StartClass("Start",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pStartCmd);

	//	Command Stop
	StopClass	*pStopCmd =
		new StopClass("Stop",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pStopCmd);

	//	Command updatePosition
	updatePositionClass	*pupdatePositionCmd =
		new updatePositionClass("updatePosition",
			Tango::DEV_USHORT, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pupdatePositionCmd);

	//	Command startContinuousAcquisition
	startContinuousAcquisitionClass	*pstartContinuousAcquisitionCmd =
		new startContinuousAcquisitionClass("startContinuousAcquisition",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pstartContinuousAcquisitionCmd);

	//	Command reset
	resetClass	*presetCmd =
		new resetClass("reset",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(presetCmd);

	/*----- PROTECTED REGION ID(ZygoZMIClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMIClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		ZygoZMIClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void ZygoZMIClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(ZygoZMIClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMIClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		ZygoZMIClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void ZygoZMIClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		ZygoZMI *dev = static_cast<ZygoZMI *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(ZygoZMIClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMIClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMIClass::get_attr_object_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *ZygoZMIClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(ZygoZMIClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	ZygoZMIClass::Additional Methods
} //	namespace
