/*----- PROTECTED REGION ID(ZygoZMIStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        ZygoZMIStateMachine.cpp
//
// description : State machine file for the ZygoZMI class
//
// project :     zygoZMI4104c
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <ZygoZMI.h>

/*----- PROTECTED REGION END -----*/	//	ZygoZMI::ZygoZMIStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  FAULT   |  interferometer in not connected
//  ALARM   |  there are errors on measurment axis
//  ON      |  interferometer is running and there is no error


namespace ZygoZMI_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI::is_axis1Position_allowed()
 *	Description : Execution allowed for axis1Position attribute
 */
//--------------------------------------------------------
bool ZygoZMI::is_axis1Position_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for axis1Position attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI::axis1PositionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::axis1PositionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI::is_axis1State_allowed()
 *	Description : Execution allowed for axis1State attribute
 */
//--------------------------------------------------------
bool ZygoZMI::is_axis1State_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for axis1State attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI::axis1StateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::axis1StateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI::is_boardVersion_allowed()
 *	Description : Execution allowed for boardVersion attribute
 */
//--------------------------------------------------------
bool ZygoZMI::is_boardVersion_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for boardVersion attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI::boardVersionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::boardVersionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI::is_boardFirmwareVersion_allowed()
 *	Description : Execution allowed for boardFirmwareVersion attribute
 */
//--------------------------------------------------------
bool ZygoZMI::is_boardFirmwareVersion_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for boardFirmwareVersion attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI::boardFirmwareVersionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::boardFirmwareVersionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI::is_gatewayBoardVersion_allowed()
 *	Description : Execution allowed for gatewayBoardVersion attribute
 */
//--------------------------------------------------------
bool ZygoZMI::is_gatewayBoardVersion_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for gatewayBoardVersion attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI::gatewayBoardVersionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::gatewayBoardVersionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI::is_gatewayFirmwareVersion_allowed()
 *	Description : Execution allowed for gatewayFirmwareVersion attribute
 */
//--------------------------------------------------------
bool ZygoZMI::is_gatewayFirmwareVersion_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for gatewayFirmwareVersion attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI::gatewayFirmwareVersionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::gatewayFirmwareVersionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI::is_flyscanAxisNbr_allowed()
 *	Description : Execution allowed for flyscanAxisNbr attribute
 */
//--------------------------------------------------------
bool ZygoZMI::is_flyscanAxisNbr_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for flyscanAxisNbr attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI::flyscanAxisNbrStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::flyscanAxisNbrStateAllowed_WRITE

	//	Not any excluded states for flyscanAxisNbr attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI::flyscanAxisNbrStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::flyscanAxisNbrStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI::is_flyscanFreq_allowed()
 *	Description : Execution allowed for flyscanFreq attribute
 */
//--------------------------------------------------------
bool ZygoZMI::is_flyscanFreq_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for flyscanFreq attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI::flyscanFreqStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::flyscanFreqStateAllowed_WRITE

	//	Not any excluded states for flyscanFreq attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI::flyscanFreqStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::flyscanFreqStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI::is_flyscanTime_allowed()
 *	Description : Execution allowed for flyscanTime attribute
 */
//--------------------------------------------------------
bool ZygoZMI::is_flyscanTime_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for flyscanTime attribute in Write access.
	/*----- PROTECTED REGION ID(ZygoZMI::flyscanTimeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::flyscanTimeStateAllowed_WRITE

	//	Not any excluded states for flyscanTime attribute in read access.
	/*----- PROTECTED REGION ID(ZygoZMI::flyscanTimeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::flyscanTimeStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI::is_Start_allowed()
 *	Description : Execution allowed for Start attribute
 */
//--------------------------------------------------------
bool ZygoZMI::is_Start_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Start command.
	/*----- PROTECTED REGION ID(ZygoZMI::StartStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::StartStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI::is_Stop_allowed()
 *	Description : Execution allowed for Stop attribute
 */
//--------------------------------------------------------
bool ZygoZMI::is_Stop_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Stop command.
	/*----- PROTECTED REGION ID(ZygoZMI::StopStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::StopStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI::is_updatePosition_allowed()
 *	Description : Execution allowed for updatePosition attribute
 */
//--------------------------------------------------------
bool ZygoZMI::is_updatePosition_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for updatePosition command.
	/*----- PROTECTED REGION ID(ZygoZMI::updatePositionStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::updatePositionStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI::is_startContinuousAcquisition_allowed()
 *	Description : Execution allowed for startContinuousAcquisition attribute
 */
//--------------------------------------------------------
bool ZygoZMI::is_startContinuousAcquisition_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for startContinuousAcquisition command.
	/*----- PROTECTED REGION ID(ZygoZMI::startContinuousAcquisitionStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::startContinuousAcquisitionStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ZygoZMI::is_reset_allowed()
 *	Description : Execution allowed for reset attribute
 */
//--------------------------------------------------------
bool ZygoZMI::is_reset_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for reset command.
	/*----- PROTECTED REGION ID(ZygoZMI::resetStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ZygoZMI::resetStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(ZygoZMI::ZygoZMIStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	ZygoZMI::ZygoZMIStateAllowed.AdditionalMethods

}	//	End of namespace
